[tools]
k9s = "latest"
kubectl = "latest"
task = "latest"
helm-ls = "latest"
helm = "latest"
gitleaks = "latest"
cocogitto = "latest"
"kkrew:tree" = "latest"
claude = "latest"

[plugins]
kkrew = "https://github.com/soupglasses/mise-krew"
